init:
  - ps: Install-Product node $env:nodejs_version

image:
  - Visual Studio 2017

matrix:
  fast_finish: true

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test

build: off
